--- /usr/lib/python2.7/dist-packages/os_brick/initiator/connector.py.org	2017-05-12 09:05:37.141473539 +0700
+++ /usr/lib/python2.7/dist-packages/os_brick/initiator/connector.py	2017-05-11 16:47:12.550339685 +0700
@@ -1869,13 +1869,15 @@
         try:
             user = connection_properties['auth_username']
             pool, volume = connection_properties['name'].split('/')
+            conf = connection_properties.get('conffile')
         except IndexError:
             msg = _("Connect volume failed, malformed connection properties")
             raise exception.BrickException(msg=msg)
 
         rbd_client = linuxrbd.RBDClient(user, pool)
         rbd_volume = linuxrbd.RBDVolume(rbd_client, volume)
-        rbd_handle = linuxrbd.RBDVolumeIOWrapper(rbd_volume)
+        rbd_handle = linuxrbd.RBDVolumeIOWrapper(
+            linuxrbd.RBDImageMetadata(rbd_volume, pool, user, conf))
         return rbd_handle
 
     def connect_volume(self, connection_properties):
